const moment = require("moment");

module.exports = Object.freeze({
  CALENDAR_INITIAL_EVENTS: [
    {
      title: "Math Test",
      theme: "GREEN",
      startTime: moment().add(-12, "d").startOf("day"),
      endTime: moment().add(-12, "d").endOf("day"),
    },
    {
      title: "Science Test",
      theme: "PINK",
      startTime: moment().add(-8, "d").startOf("day"),
      endTime: moment().add(-8, "d").endOf("day"),
    },
    {
      title: "History Test",
      theme: "PURPLE",
      startTime: moment().add(-2, "d").startOf("day"),
      endTime: moment().add(-2, "d").endOf("day"),
    },
    {
      title: "English Test",
      theme: "BLUE",
      startTime: moment().startOf("day"),
      endTime: moment().endOf("day"),
    },
    {
      title: "Geography Test",
      theme: "GREEN",
      startTime: moment().startOf("day"),
      endTime: moment().endOf("day"),
    },
    {
      title: "Chemistry Test",
      theme: "PURPLE",
      startTime: moment().startOf("day"),
      endTime: moment().endOf("day"),
    },
    {
      title: "Physics Test",
      theme: "ORANGE",
      startTime: moment().add(3, "d").startOf("day"),
      endTime: moment().add(3, "d").endOf("day"),
    },
    {
      title: "Biology Test",
      theme: "PINK",
      startTime: moment().add(5, "d").startOf("day"),
      endTime: moment().add(5, "d").endOf("day"),
    },
    {
      title: "Economics Test",
      theme: "GREEN",
      startTime: moment().add(8, "d").startOf("day"),
      endTime: moment().add(8, "d").endOf("day"),
    },
    {
      title: "Psychology Test",
      theme: "ORANGE",
      startTime: moment().add(8, "d").startOf("day"),
      endTime: moment().add(8, "d").endOf("day"),
    },
    {
      title: "Sociology Test",
      theme: "PINK",
      startTime: moment().add(8, "d").startOf("day"),
      endTime: moment().add(8, "d").endOf("day"),
    },
    {
      title: "Literature Test",
      theme: "GREEN",
      startTime: moment().add(8, "d").startOf("day"),
      endTime: moment().add(8, "d").endOf("day"),
    },
    {
      title: "Philosophy Test",
      theme: "BLUE",
      startTime: moment().add(12, "d").startOf("day"),
      endTime: moment().add(12, "d").endOf("day"),
    },
    {
      title: "Art Test",
      theme: "PURPLE",
      startTime: moment().add(16, "d").startOf("day"),
      endTime: moment().add(16, "d").endOf("day"),
    },
  ],

  RECENT_TRANSACTIONS: [
    {
      name: "TechCorp",
      avatar: "https://logo.clearbit.com/techcorp.com",
      email: "contact@techcorp.com",
      location: "Paris",
      amount: 5,
      date: moment().endOf("day"),
    },
    {
      name: "InnovateX",
      avatar: "https://logo.clearbit.com/innovatex.com",
      email: "contact@innovatex.com",
      location: "London",
      amount: 8,
      date: moment().add(-1, "d").endOf("day"),
    },
    {
      name: "GlobalSolutions",
      avatar: "https://logo.clearbit.com/globalsolutions.com",
      email: "contact@globalsolutions.com",
      location: "Canada",
      amount: 12,
      date: moment().add(-1, "d").endOf("day"),
    },
    {
      name: "MatrixSystems",
      avatar: "https://logo.clearbit.com/matrixsystems.com",
      email: "contact@matrixsystems.com",
      location: "Peru",
      amount: 7,
      date: moment().add(-1, "d").endOf("day"),
    },
    {
      name: "SupportHub",
      avatar: "https://logo.clearbit.com/supporthub.com",
      email: "contact@supporthub.com",
      location: "London",
      amount: 10,
      date: moment().add(-2, "d").endOf("day"),
    },
    {
      name: "MiyaServices",
      avatar: "https://logo.clearbit.com/miyaservices.com",
      email: "contact@miyaservices.com",
      location: "Paris",
      amount: 6,
      date: moment().add(-2, "d").endOf("day"),
    },
    {
      name: "SupportHub",
      avatar: "https://logo.clearbit.com/supporthub.com",
      email: "contact@supporthub.com",
      location: "Canada",
      amount: 9,
      date: moment().add(-2, "d").endOf("day"),
    },
    {
      name: "MatrixSystems",
      avatar: "https://logo.clearbit.com/matrixsystems.com",
      email: "contact@matrixsystems.com",
      location: "London",
      amount: 11,
      date: moment().add(-2, "d").endOf("day"),
    },
    {
      name: "InnovateX",
      avatar: "https://logo.clearbit.com/innovatex.com",
      email: "contact@innovatex.com",
      location: "Tokyo",
      amount: 14,
      date: moment().add(-2, "d").endOf("day"),
    },
    {
      name: "GlobalSolutions",
      avatar: "https://logo.clearbit.com/globalsolutions.com",
      email: "contact@globalsolutions.com",
      location: "Paris",
      amount: 6,
      date: moment().add(-2, "d").endOf("day"),
    },
    {
      name: "SupportHub",
      avatar: "https://logo.clearbit.com/supporthub.com",
      email: "contact@supporthub.com",
      location: "Canada",
      amount: 15,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "MatrixSystems",
      avatar: "https://logo.clearbit.com/matrixsystems.com",
      email: "contact@matrixsystems.com",
      location: "US",
      amount: 13,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "InnovateX",
      avatar: "https://logo.clearbit.com/innovatex.com",
      email: "contact@innovatex.com",
      location: "Tokyo",
      amount: 16,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "GlobalSolutions",
      avatar: "https://logo.clearbit.com/globalsolutions.com",
      email: "contact@globalsolutions.com",
      location: "London",
      amount: 9,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "SupportHub",
      avatar: "https://logo.clearbit.com/supporthub.com",
      email: "contact@supporthub.com",
      location: "Paris",
      amount: 7,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "MiyaServices",
      avatar: "https://logo.clearbit.com/miyaservices.com",
      email: "contact@miyaservices.com",
      location: "Canada",
      amount: 12,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "MatrixSystems",
      avatar: "https://logo.clearbit.com/matrixsystems.com",
      email: "contact@matrixsystems.com",
      location: "London",
      amount: 18,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "SupportHub",
      avatar: "https://logo.clearbit.com/supporthub.com",
      email: "contact@supporthub.com",
      location: "Tokyo",
      amount: 11,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "InnovateX",
      avatar: "https://logo.clearbit.com/innovatex.com",
      email: "contact@innovatex.com",
      location: "Paris",
      amount: 10,
      date: moment().add(-3, "d").endOf("day"),
    },
  ],
});
